backend/controllers/PartnerController.php
<?php

namespace backend\controllers;

use common\models\PartnerDescription;
use Yii;
use common\models\Partner;
use common\models\PartnerSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PartnerController implements the CRUD actions for Partner model.
 */
class PartnerController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Partner models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PartnerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Partner model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Partner model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Partner();
        $model_partner_description = new PartnerDescription();

        if ($model->load(Yii::$app->request->post())) {

            if (empty($model->slug)) {
                $model->title = Yii::$app->request->post()["PartnerDescription"][0]['title'];
            }

            if ($model->save()) {

                if (Yii::$app->request->post()["PartnerDescription"]) {
                    foreach (Yii::$app->request->post()["PartnerDescription"] AS $language_id => $description) {
                        $partner_description = new PartnerDescription();
                        $partner_description->partner_id = $model->id;
                        $partner_description->language_id = $language_id;
                        $partner_description->title = $description['title'];
                        $partner_description->description = $description['description'];
                        $partner_description->short_description = $description['short_description'];
                        $partner_description->meta_title = $description['meta_title'];
                        $partner_description->meta_description = $description['meta_description'];
                        $partner_description->meta_keyword = $description['meta_keyword'];

                        $partner_description->save();
                    }
                }

                return $this->redirect(['view', 'id' => $model->id]);
            }

        }

        return $this->render('create', [
            'model' => $model,
            'model_partner_description' => $model_partner_description,
        ]);
    }
    /**
     * Updates an existing Partner model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model_partner_description = new PartnerDescription();
        if ($model->load(Yii::$app->request->post())) {

            if (empty($model->slug)) {
                $model->title = Yii::$app->request->post()["PartnerDescription"][0]['title'];
            }

            if ($model->save()) {

                PartnerDescription::deleteAll(array('partner_id' => $model->id));

                foreach (Yii::$app->request->post()["PartnerDescription"] AS $language_id => $description) {
                    $partner_description = new PartnerDescription();
                    $partner_description->partner_id = $model->id;
                    $partner_description->language_id = $language_id;
                    $partner_description->title = $description['title'];
                    $partner_description->description = $description['description'];
                    $partner_description->short_description = $description['short_description'];
                    $partner_description->meta_title = $description['meta_title'];
                    $partner_description->meta_description = $description['meta_description'];
                    $partner_description->meta_keyword = $description['meta_keyword'];

                    $partner_description->save();
                }

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'model_partner_description' => $model_partner_description,
        ]);
    }

    /**
     * Deletes an existing Partner model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        PartnerDescription::deleteAll(array('partner_id' => $id));

        return $this->redirect(['index']);
    }

    /**
     * Finds the Partner model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Partner the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Partner::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\widgets\ActiveForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }


    /**
     * @inheritdoc
     */

    public function actionGallery()
    {
        return $this->render('gallery');
    }

    /**
     * @inheritdoc
     */
    public function actionNews()
    {
        return $this->render('news');
    }

    /**
     * @inheritdoc
     */
    public function actionAnswer()
    {
        return $this->render('answer');
    }

    /**
     * @inheritdoc
     */
    public function actionArchive()
    {
        return $this->render('archive');
    }

    /**
     * @inheritdoc
     */
    public function actionArticle()
    {
        return $this->render('article');
    }

    /**
     * @inheritdoc
     */
    public function actionHistory()
    {
        return $this->render('history');
    }

    /**
     * @inheritdoc
     */
    public function actionManagement()
    {
        return $this->render('management');
    }

    /**
     * @inheritdoc
     */
    public function actionQuiz()
    {
        return $this->render('quiz');
    }


    /**
     * @inheritdoc
     */
    public function actionRate()
    {
        return $this->render('rate');
    }

    /**
     * @inheritdoc
     */
    public function actionReport()
    {
        return $this->render('report');
    }

    /**
     * @inheritdoc
     */
    public function actionStructure()
    {
        return $this->render('structure');
    }

    /**
     * @inheritdoc
     */
    public function actionVideo()
    {
        return $this->render('video');
    }

    /**
     * @inheritdoc
     */
    public function actionZakupki()
    {
        return $this->render('zakupki');
    }
    /**
     * @inheritdoc
     */
    public function actionSManagement()
    {
        return $this->render('smanagement');
    }

    /**
     * @inheritdoc
     */
    public function actionCabinetData()
    {
        return $this->render('cabinetData');
    }

    /**
     * @inheritdoc
     */
    public function actionCabinetIndications()
    {
        return $this->render('cabinetIndications');
    }

    /**
     * @inheritdoc
     */
    public function actionCabinetPay()
    {
        return $this->render('cabinetPay');
    }

    /**
     * @inheritdoc
     */
    public function actionCabinetQuotation()
    {
        return $this->render('cabinetQuotation');
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $model = new LoginForm();


        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            if (!Yii::$app->user->isGuest) {
                return array('status' => 'success');
            }

            $validate = ActiveForm::validate($model);
            if ($validate) {
                return array('validate' => $validate);
            }

            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                return array('status' => 'success');
            } else {
                return array('status' => 'error');
            }

        }

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;


            $validate = ActiveForm::validate($model);
            if ($validate) {
                return array('validate' => $validate);
            }

            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                return array('success' => 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                return array('error' => 'There was an error sending your message.');
            }

        }


        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact1', [
                'model' => $model,
            ]);
        }

        return $this->render('contact1');
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionTest()
    {
        return $this->render('test');
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionPartners()
    {
        return $this->render('partners');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;


            $validate = ActiveForm::validate($model);
            if ($validate) {
                return array('validate' => $validate);
            }

            if ($model->load(Yii::$app->request->post())) {
                if ($user = $model->signup()) {
                    if (Yii::$app->getUser()->login($user)) {
                        return array('status' => 'success');
                    }
                }
            }

        }

        if ($model->load(Yii::$app->request->post())) {

            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();


        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            $validate = ActiveForm::validate($model);
            if ($validate) {
                return array('validate' => $validate);
            }

            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                if ($model->sendEmail()) {
                    Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                } else {
                    Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
                }
                return array('status' => 'success');
            }

        }


        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**

frontend/views/partner/_images.php
<?php
use himiklab\thumbnail\EasyThumbnailImage;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

/**
 * <?= $this->render('_gallery', [
'model' => $model
]) ?>
 */
?>

<div class="row">
    <div class="col-xs-12">

        <?php foreach($model->images as $image) {?>
            <div class="col-xs-6 col-sm-3 col-md-2">
                <div class="row">

                    <?php
                    echo newerton\fancybox\FancyBox::widget([
                        'target' => 'a.fancybox',
                        'helpers' => true,
                        'mouse' => true,
                        'config' => [
                            'maxWidth' => '90%',
                            'maxHeight' => '90%',
                            'playSpeed' => 3000,
                            'padding' => 0,
                            'fitToView' => false,
                            // 'width' => '70%',
                            // 'height' => '70%',
                            // 'autoSize' => false,
                            'closeClick' => false,
//                            'openEffect' => 'elastic',
//                            'closeEffect' => 'elastic',
//                            'prevEffect' => 'elastic',
//                            'nextEffect' => 'elastic',
                            'closeBtn' => false,
                            'openOpacity' => true,
                            'helpers' => [
                                'title' => ['type' => 'float'],
                                'buttons' => [],
                                'thumbs' => ['width' => 68, 'height' => 50],
                                'overlay' => [
                                    'css' => [
                                        'background' => 'rgba(0, 0, 0, 0.8)'
                                    ]
                                ]
                            ],
                        ]
                    ]);
                    echo Html::a(
                        Html::img($image->image, ['class' => 'img-responsive']),
                        $image->image, ['rel' => 'group', 'class' => 'fancybox']);
                    ?>

                </div>
            </div>
        <?php }?>

    </div>
</div>

frontend/views/partner/_item.php
<?php
use himiklab\thumbnail\EasyThumbnailImage;
use yii\helpers\Url;
?>

<div class="col-xs-12 col-sm-4 col-md-3">
    <div class="thumbnail">
        <?=
        EasyThumbnailImage::thumbnailImg(
            $model->imagePath,
            400,
            300,
            EasyThumbnailImage::THUMBNAIL_OUTBOUND,
            [
                'alt' => $model->title,
                'class' => 'img-responsive'
            ]
        );
        ?>
        <div class="caption">
            <h3><?= $model->title ?></h3>
            <?php $anounce = strip_tags($model->anounce, '<a>'); echo mb_substr($anounce,0, 200, 'UTF-8').' ...'; ?>
            <p>
                <div class="btn btn-default" ><?= Yii::$app->formatter->asDate($model->created, 'dd.MM.yyyy') ?></div>
                <a href="<?= Url::toRoute(['/article/view', 'slug' => $model->slug]) ?>" class="btn btn-primary">Подробнее</a>
            </p>
        </div>
    </div>
</div>

frontend/views/partner/_navCompany.php
<?

use \yii\helpers\Url;

?>

<div class="info-menu">
    <div class="info-menu-title text-uppercase"><?= $title; ?></div>
    <div class="info-menu-list">
        <div class="info-menu-item">
            <a href="<?= Url::toRoute(['site/management']); ?>" class="info-menu-link">Руководство</a>
        </div>
        <div class="info-menu-item">
            <a href="<?= Url::toRoute(['site/structure']); ?>" class="info-menu-link">Структура</a>
        </div>
        <div class="info-menu-item">
            <a href="<?= Url::toRoute(['site/history']); ?>" class="info-menu-link">История</a>
        </div>
        <div class="info-menu-item">
            <a href="<?= Url::toRoute(['site/s-management']); ?>" class="info-menu-link">Интегрированная система
                менеджмента </a>
        </div>
        <div class="info-menu-item">
            <a href="<?= Url::toRoute(['site/partners']); ?>" class="info-menu-link">Партнеры</a>
        </div>
    </div>
</div>

frontend/views/partner/index.php
<?php

use yii\helpers\Url;

/* @var $this yii\web\View */
$this->title = 'Статьи';

$this->params['breadcrumbs'][] = 'Партнеры';
$this->registerMetaTag(['name' => 'keywords', 'content' => 'Партнеры']);
$this->registerMetaTag(['name' => 'description', 'content' => 'Партнеры']);

?>
<div class="navigation">
    <div class="container">
        <ol class="breadcrumb navigation-breadcrumb">
            <li><a href="#" class="navigation-breadcrumb-link">Главная</a></li>
            <li class="active">Партнеры</li>
        </ol>
        <h1 class="text-uppercase navigation-title">ПАРТНЕРЫ</h1>
    </div>
</div>

<div class="main">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <?= $this->render('_navCompany', [
                    'title' => 'Партнеры'
                ]); ?>
            </div>
            <div class="col-md-9">
                <div class="main-container">
                    <div class="report">
                        <div class="report-date bg-white">
                            <div class="text-uppercase report-title text-center">ПАРТНЕРЫ
                            </div>
                            <div class="report-body">
                                <? if (isset($data) && is_array($data)): ?>
                                    <? foreach ($data AS $id => $item): ?>
                                        <div class="panel panel-default">

                                            <div class="panel-heading" role="tab" id="heading-<?= $id; ?>">
                                                <h4 class="panel-title">
                                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                                       href="#collapse-<?= $id; ?>" aria-expanded="true"
                                                       aria-controls="collapse-<?= $id; ?>">
                                                        <?= $item['category']['name']; ?>
                                                    </a>
                                                </h4>
                                            </div>
                                            <? if (isset($item['partner'])): ?>
                                                <div id="collapse-<?= $id; ?>" class="panel-collapse collapse"
                                                     role="tabpanel"
                                                     aria-labelledby="heading-<?= $id; ?>">
                                                    <div class="panel-body">

                                                        <ul class="list-group">
                                                            <? foreach ($item['partner'] AS $partner): ?>
                                                                <li class="list-group-item">
                                                                    <a href="<?= Url::toRoute(['partner/view', 'id' => $partner['partner_id']]); ?>"><?= $partner['title']; ?></a>
                                                                </li>
                                                            <? endforeach; ?>
                                                        </ul>

                                                    </div>
                                                </div>
                                            <? endif; ?>
                                        </div>
                                    <? endforeach; ?>
                                <? endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<?= \frontend\widgets\CallBack::widget(); ?>

<?= \frontend\widgets\Info::widget(); ?>

<link rel="stylesheet" href="/css/history.css">

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <?= \yii\widgets\Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
        </div>
    </div>
</div>

frontend/views/partner/view.php
<?php

use frontend\widgets\ProductWidget;
use yii\helpers\Url;

/** @var $model \common\models\Article */
$this->title = $model->meta_title ? $model->meta_title : $model->title;
$this->registerMetaTag(['name' => 'keywords', 'content' => $model->meta_keyword]);
$this->registerMetaTag(['name' => 'description', 'content' => $model->meta_description]);

$this->params['breadcrumbs'][] = $model->title;
?>

<div class="navigation">
    <div class="container">
        <ol class="breadcrumb navigation-breadcrumb">
            <li><a href="/" class="navigation-breadcrumb-link">Главная</a></li>
            <li><a href="<?= Url::toRoute(['partner/index']); ?>" class="navigation-breadcrumb-link">Партнеры</a></li>
            <li class="active"><?= $model->title; ?></li>
        </ol>
        <h1 class="text-uppercase navigation-title"><?= $model->title; ?></h1>
    </div>
</div>

<div class="main">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <?= $this->render('_navCompany', [
                    'title' => 'Интегрированная система менеджмента'
                ]) ?>
            </div>
            <div class="col-md-9">
                <div class="main-container">
                    <div class="report">
                        <div class="report-date bg-white">
                            <div class="text-uppercase report-title text-center"><?= $model->title; ?></div>
                            <div class="report-body">
                                <?= $model->description; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?= \frontend\widgets\CallBack::widget(); ?>

<?= \frontend\widgets\Info::widget(); ?>

<link rel="stylesheet" href="/css/history.css">